// flow-typed signature: 59882f0e08ea69eb694b01d964034f11
// flow-typed version: <<STUB>>/react-native-router-flux_v4.0.0-beta.31/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-router-flux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-router-flux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-router-flux/__tests__/scenes.test' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/ActionConst' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Drawer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/index' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Lightbox' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/LightboxNavigator' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Modal' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/NavBar' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/navigationStore' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Overlay' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/OverlayNavigator' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/pathParser' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Reducer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Router' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Scene' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Stack' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/State' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Tabs' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/dist/Util' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/ActionConst' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Drawer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/index' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Lightbox' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/LightboxNavigator' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Modal' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/NavBar' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/navigationStore' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Overlay' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/OverlayNavigator' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/pathParser' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Reducer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Router' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Scene' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Stack' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/State' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Tabs' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Util' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-router-flux/__tests__/scenes.test.js' {
  declare module.exports: $Exports<'react-native-router-flux/__tests__/scenes.test'>;
}
declare module 'react-native-router-flux/dist/ActionConst.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/ActionConst'>;
}
declare module 'react-native-router-flux/dist/Drawer.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Drawer'>;
}
declare module 'react-native-router-flux/dist/index.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/index'>;
}
declare module 'react-native-router-flux/dist/Lightbox.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Lightbox'>;
}
declare module 'react-native-router-flux/dist/LightboxNavigator.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/LightboxNavigator'>;
}
declare module 'react-native-router-flux/dist/Modal.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Modal'>;
}
declare module 'react-native-router-flux/dist/NavBar.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/NavBar'>;
}
declare module 'react-native-router-flux/dist/navigationStore.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/navigationStore'>;
}
declare module 'react-native-router-flux/dist/Overlay.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Overlay'>;
}
declare module 'react-native-router-flux/dist/OverlayNavigator.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/OverlayNavigator'>;
}
declare module 'react-native-router-flux/dist/pathParser.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/pathParser'>;
}
declare module 'react-native-router-flux/dist/Reducer.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Reducer'>;
}
declare module 'react-native-router-flux/dist/Router.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Router'>;
}
declare module 'react-native-router-flux/dist/Scene.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Scene'>;
}
declare module 'react-native-router-flux/dist/Stack.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Stack'>;
}
declare module 'react-native-router-flux/dist/State.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/State'>;
}
declare module 'react-native-router-flux/dist/Tabs.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Tabs'>;
}
declare module 'react-native-router-flux/dist/Util.js' {
  declare module.exports: $Exports<'react-native-router-flux/dist/Util'>;
}
declare module 'react-native-router-flux/src/ActionConst.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/ActionConst'>;
}
declare module 'react-native-router-flux/src/Drawer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Drawer'>;
}
declare module 'react-native-router-flux/src/index.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/index'>;
}
declare module 'react-native-router-flux/src/Lightbox.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Lightbox'>;
}
declare module 'react-native-router-flux/src/LightboxNavigator.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/LightboxNavigator'>;
}
declare module 'react-native-router-flux/src/Modal.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Modal'>;
}
declare module 'react-native-router-flux/src/NavBar.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/NavBar'>;
}
declare module 'react-native-router-flux/src/navigationStore.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/navigationStore'>;
}
declare module 'react-native-router-flux/src/Overlay.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Overlay'>;
}
declare module 'react-native-router-flux/src/OverlayNavigator.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/OverlayNavigator'>;
}
declare module 'react-native-router-flux/src/pathParser.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/pathParser'>;
}
declare module 'react-native-router-flux/src/Reducer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Reducer'>;
}
declare module 'react-native-router-flux/src/Router.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Router'>;
}
declare module 'react-native-router-flux/src/Scene.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Scene'>;
}
declare module 'react-native-router-flux/src/Stack.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Stack'>;
}
declare module 'react-native-router-flux/src/State.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/State'>;
}
declare module 'react-native-router-flux/src/Tabs.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Tabs'>;
}
declare module 'react-native-router-flux/src/Util.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Util'>;
}
declare module 'react-native-router-flux/test/setup.js' {
  declare module.exports: $Exports<'react-native-router-flux/test/setup'>;
}
